[project]
name = "edl-manager"
version = "0.1.0"
description = "A simple EDL manager for Firewalls"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipaddress>=1.0.23",
    "pandas>=2.2.3",
]
